remove the method and its references
NVIDIA/cuda-python pull request #203
Opened 2024-10-30 22:12 UTC by ksimpson-work

from issue:

The obvious issue is that both of these call get_device_from_ctx which references the unimported Device(). Importing it would cause a circular dependency. This does not appear to be the root of the issue, as per the logic of the Stream class, and the cuda model, self._device_id can never be None. In short, we can get rid of util.device_from_ctx

close #202 
/ok to test

2024-10-30 22:13 UTC, ksimpson-work commented
/ok to test

2024-10-31 01:26 UTC, leofang requested changes
I am not sure I follow. `self._device_id` could be `None` if we wrap a foreign stream using `Device.create_stream(some_foreign_stream_object)`. Then, the `cuStreamGetCtx` ->  (set to the stream ctx) ->`cuCtxGetDevice` -> (set back to original ctx) combo is the only way to reliably retrieve the device ID. `get_device_from_ctx` is meant to make this combo cleaner.

How did you encounter a circular dependency? It would be a miss of our test suite depending on the trigger path. It is true that we forgot to import `Device` in `get_device_from_ctx` (good catch!), but circular dependency can be easily resolved by importing the object inside the function, as is already done in `Stream.device`.

2024-10-31 17:46 UTC, ksimpson-work commented
Thankyou for pointing out my oversight. I now clearly see that device_id is None when a foreign stream is provided. There are still some issues which I will seek to address, and will switch this from draft once I get it working / identify the problem.

2024-10-31 18:14 UTC, ksimpson-work commented
The changes 

import Device inside function to avoid circular import
handle -> _handle
compare int(ctx) based on:

cdef class CUcontext:
    """

    A regular context handle

    Methods
    -------
    getPtr()
        Get memory address of class instance

    """
    def __cinit__(self, void_ptr init_value = 0, void_ptr _ptr = 0):
        if _ptr == 0:
            self._ptr = &self.__val
            self._ptr[0] = <cydriver.CUcontext>init_value
        else:
            self._ptr = <cydriver.CUcontext *>_ptr
    def __init__(self, *args, **kwargs):
        pass
    def __repr__(self):
        return '<CUcontext ' + str(hex(self.__int__())) + '>'
    def __index__(self):
        return self.__int__()
    def __int__(self):
        return <void_ptr>self._ptr[0]
    def getPtr(self):
        return <void_ptr>self._ptr

2024-11-02 00:01 UTC, leofang requested changes
LGTM, blocking the merge until we conclude beta 1 QA process.

2024-11-02 00:01 UTC, leofang commented on cuda_core/tests/test_stream.py
> +    context = stream.context
Let's merge the two tests by dropping the common parts and renaming the test. Let's also not use private APIs starting with new tests (so that we can limit the scope of #196). I also added an assert.
```suggestion
def test_stream_from_foreign_stream():
    device = Device()
    other_stream = device.create_stream(options=StreamOptions())
    stream = device.create_stream(obj=other_stream)
    assert other_stream.handle == stream.handle
    device = stream.device
    assert isinstance(device, Device)
    context = stream.context
```

2024-11-12 00:51 UTC, leofang approved these changes

2024-11-12 17:25 UTC, merged