Clean up testsuite
NVIDIA/cuda-python pull request #213
Opened 2024-11-04 18:42 UTC by ksimpson-work

Clean up the testsuite by:

1. Removing calls to internal entry-points in favour of public ones. 
2. Updating the use of fixtures to handle context initialization on a per-test basis. This includes a function level fixture to init, and then subsequently de-init when calling a method which requirtes context initalization (usually via device.set_current()). It also includes a module level fixture which ensures that each module starts with an uninitialized context.

2024-11-04 18:43 UTC, ksimpson-work commented
/ok to test

2024-11-15 01:35 UTC, leofang requested changes
Thanks, Keenan, left some nits.

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/conftest.py
>  from cuda.core.experimental._device import Device
I think `Device` is public API, no need to access it through a private module:
```suggestion
from cuda.core.experimental import Device
```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/conftest.py
> +from cuda import cuda
nit: future proof
```suggestion
try:
    from cuda.bindings import driver
except ImportError:
    from cuda import cuda as driver
```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/conftest.py
> +    handle_return(cuda.cuCtxPopCurrent())
```suggestion
    handle_return(driver.cuCtxPopCurrent())

```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/conftest.py
> +    handle_return(cuda.cuCtxPopCurrent())
```suggestion
    handle_return(driver.cuCtxPopCurrent())

```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/test_device.py
>  from cuda.core.experimental._device import Device
ditto
```suggestion
from cuda.core.experimental import Device
```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/test_event.py
>  from cuda.core.experimental._device import Device
ditto
```suggestion
from cuda.core.experimental import Device, EventOptions
```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/test_event.py
>      assert isinstance(event.handle, int)
nit: I think we should just move the assert to one of the tests. The test body overlaps with other tests.

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/test_event.py
> +def test_is_timing_disabled(init_cuda):
Let's call it `test_timing` and parametrize this test with 3 `timing` options: `None`, `True`, `False`. Specialize a case for `None`: We need to test the default (without any `EventOptions`) is no timing (IIRC).

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/test_launcher.py
>  from cuda.core.experimental._device import Device
nit
```suggestion
from cuda.core.experimental import Device, LaunchConfig
from cuda.core.experimental._stream import Stream
```

2024-11-15 01:35 UTC, leofang commented on cuda_core/tests/test_program.py
>  from cuda.core.experimental._program import Program
nit
```suggestion
from cuda.core.experimental import Program
```

2024-11-15 18:22 UTC, ksimpson-work commented
Thanks @leofang for those comments. I addressed all of them and made the changes.

2024-11-16 03:12 UTC, leofang approved these changes
Thanks, Keenan! Left 3 nits, feel free to merge after addressing them.

2024-11-16 03:12 UTC, leofang commented on cuda_core/tests/conftest.py
> +        del _device._tls.devices
nit: let's try not to duplicate code
```suggestion
    _device_unset_current()

def _device_unset_current():
    handle_return(driver.cuCtxPopCurrent())
    with _device._tls_lock:
        del _device._tls.devices

@pytest.fixture(scope="function")
def deinit_cuda():
    yield
    _device_unset_current()
```

2024-11-16 03:12 UTC, leofang commented on cuda_core/tests/test_device.py
> +    from cuda import cudart as runtime
nit
```suggestion
try:
    from cuda.bindings import driver, runtime
except ImportError:
    from cuda import cuda as driver
    from cuda import cudart as runtime
```

2024-11-16 03:12 UTC, leofang commented on cuda_core/tests/test_stream.py
>      stream.wait(event)  # Should not raise any exceptions
we can actually test the real-world use case (also get rid of `Event._init()`):
```suggestion
def test_stream_wait_event(init_cuda):
    s1 = Device().create_stream()
    s2 = Device().create_stream()
    e1 = s1.record()
    s2.wait(e1)  # Should not raise any exceptions
    s2.sync()
```

2024-11-18 19:52 UTC, vzhurba01 approved these changes

2024-11-18 19:53 UTC, merged