Add the cuda.core.experimental.system singleton
NVIDIA/cuda-python pull request #256
Opened 2024-11-28 00:46 UTC by keenan-simpson

Add the cuda.core.experiemental.system singleton which is an instance of System.

closes #149

2024-11-30 03:55 UTC, leofang requested changes
Thanks, Keenan! Left a few quick comments.

2024-11-30 03:55 UTC, leofang commented on cuda_core/docs/source/api_private.rst
> +   _system.System
👍

2024-11-30 03:55 UTC, leofang commented on cuda_core/docs/source/release.md
> +    0.2.0 <release/0.2.0-notes>
```suggestion
    0.1.1 <release/0.1.1-notes>
```

2024-11-30 03:55 UTC, leofang commented on cuda_core/docs/source/release/0.2.0-notes.md
rename this to `0.1.1-notes.md`

2024-11-30 03:55 UTC, leofang commented on cuda_core/docs/source/release/0.2.0-notes.md
> +- Addition of the system singleton
```suggestion
- Add a `cuda.core.experimental.system` module for querying system- or process- wide information.
```

2024-11-30 03:55 UTC, leofang commented on cuda_core/tests/test_system.py
> +    assert system1 is system2, "system is not a singleton"
this is only testing the Python alias which would always be true, if we really want to test the singleton property we should instantiate two `System` instances and observe that `id(sys1) == id(sys2)`.

2024-12-07 06:23 UTC, leofang commented on cuda_core/docs/source/api_private.rst
> +   _system.System
```suggestion
```

2024-12-07 06:26 UTC, leofang requested changes
@ksimpson-work I "hacked" the docs in commit 1a3f1e6. It's not pretty but it does the job:
![截圖 2024-12-07 上午1 22 45](https://github.com/user-attachments/assets/e6835fb9-a178-47a3-a8de-0991024fdd1b)

One improvement we need to make: We need to rewrite the docstrings as a one-liner, as opposed to a legal Sphinx docstring. It is because the `autodata` directive only expects simple one-liners:
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#automatically-document-attributes-or-data

2024-12-07 06:31 UTC, leofang commented on cuda_core/docs/source/conf.py
> +            lines.pop(0)
try this?
```suggestion
        lines.clear()
        lines.extend(lines_new)
```

2024-12-09 20:08 UTC, ksimpson-work commented
![Screenshot 2024-12-09 120806](https://github.com/user-attachments/assets/8b0fd967-db93-44fe-8d20-5f960ca4c2be)

2024-12-09 20:09 UTC, ksimpson-work commented
latest commit fixes the build warning and properly formats the Returns field. Thanks for the hack @leofang

2024-12-10 20:38 UTC, leofang approved these changes
Thanks!

2024-12-10 20:38 UTC, merged