multi gpu example
NVIDIA/cuda-python pull request #304
Opened 2024-12-16 12:15 UTC by amwi04

1. GPU will perform vector_add
2.  GPU will perform vector_substract

2024-12-16 22:14 UTC, vzhurba01 commented on cuda_core/examples/simple_multi_gpu_example.py
> https://github.com/NVIDIA/cuda-python/tree/main/cuda_core#code-linting

Could you run this through a linter? Looks like it should give some common formatting improvements like removing unused imports.

2024-12-16 22:14 UTC, vzhurba01 commented on cuda_core/examples/simple_multi_gpu_example.py
> +grid1 = (size + block - 1) // block
Since the grids are identical, lets have them share the same `grid` variable.

2024-12-16 22:14 UTC, vzhurba01 commented on cuda_core/examples/simple_multi_gpu_example.py
> +# Validate  result
extra whitespace

2024-12-17 04:40 UTC, leofang requested changes
Thanks, Amod! I left some comments.

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +from cuda import cuda, cudart, nvrtc
This is unused (and will be removed once you run pre-commit as Vlad suggested above IIRC).

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +# coding: utf-8
Please kindly copy the header from other examples.

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +# allocate memory to GPU0
```suggestion
# Allocate memory to GPU0
# Note: This runs on CuPy's current stream
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +# allocate memory to GPU1
```suggestion
# Allocate memory to GPU1
# Note: This runs on CuPy's current stream
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +                           size_t N) {
nit: We already introduced the name expression ideas in other examples, let's try to focus on simple things and not throw multiple things to users to learn
```suggestion
extern "C"
__global__ void vector_add(const float* A,
                           const float* B,
                           float* C,
                           size_t N) {
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +                           size_t N) {
ditto
```suggestion
extern "C"
__global__ void vector_sub(const float* A,
                           const float* B,
                           float* C,
                           size_t N) {
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +    name_expressions=("vector_add<float>",))
nits:
1. construct the arch string explicitly
2. remove `name_expressions`
```suggestion
arch0 = "".join(f"{i}" for i in dev0.compute_capability)
prog_add = Program(code_add, code_type="c++")
mod_add = prog_add.compile(
    "cubin",
    options=("-std=c++17", "-arch=sm_" + arch0,))
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +ker_add = mod_add.get_kernel("vector_add<float>")
ditto
```suggestion
ker_add = mod_add.get_kernel("vector_add")
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +    name_expressions=("vector_sub<float>",))
ditto
```suggestion
arch1 = "".join(f"{i}" for i in dev1.compute_capability)
prog_sub = Program(code_sub, code_type="c++")
mod_sub = prog_sub.compile(
    "cubin",
    options=("-std=c++17", "-arch=sm_" + arch1,))
```

2024-12-17 04:40 UTC, leofang commented on cuda_core/examples/simple_multi_gpu_example.py
> +ker_sub = mod_sub.get_kernel("vector_sub<float>")
```suggestion
ker_sub = mod_sub.get_kernel("vector_sub")
```

2025-01-02 17:42 UTC, leofang commented
/ok to test

2025-01-02 17:44 UTC, leofang submitted a review, later dismissed

2025-01-02 23:07 UTC, leofang commented
/ok to test

2025-01-02 23:08 UTC, leofang commented
/ok to test

2025-01-03 00:20 UTC, leofang approved these changes
Thanks for help @amwi04! Let's merge.

2025-01-03 00:20 UTC, merged