switch the launch argument order
NVIDIA/cuda-python pull request #316
Opened 2024-12-19 19:17 UTC by ksimpson-work

close #306 

flip the launch args

2024-12-29 00:08 UTC, leofang commented
/ok to test

2025-01-01 22:01 UTC, ksimpson-work commented
/ok to test

2025-01-02 00:30 UTC, leofang commented
Let's hold off merging for now. We need to wait for Bryce's update on the kernel spec.

2025-01-16 18:28 UTC, ksimpson-work commented
/ok to test

2025-01-17 16:09 UTC, leofang commented
> Let's hold off merging for now. We need to wait for Bryce's update on the kernel spec.

@brycelelbach

2025-02-20 07:12 UTC, leofang commented
I think we've waited long enough (>1 month). Let us not include this PR in the beta 3 release, and unset the priority until we get clarity from Andy or Bryce or Keith.

2025-02-27 23:49 UTC, leofang commented
Update: Discussed with Bryce and Keith offline, we want to get this PR included in beta 3.

2025-02-27 23:49 UTC, leofang commented
/ok to test

2025-02-27 23:50 UTC, leofang commented on cuda_core/docs/source/release/0.2.0-notes.rst
> +- The positional arguments to :meth:`~launch` are swapped, so the signature is now ``(config, kernel, *kernel_args)``
```suggestion
- The positional arguments to :func:`~launch` are swapped, so the signature is now ``(config, kernel, *kernel_args)``
```

2025-03-01 16:16 UTC, leofang commented
/ok to test

2025-03-02 03:06 UTC, leofang commented
TODO: Finalize the discussion on if we also want to pull out `stream` from config: `launch(stream, config, kernel, *args)`.

2025-03-03 20:59 UTC, vzhurba01 commented
/ok to test

2025-03-03 21:27 UTC, leofang requested changes
LGTM overall, thanks Vlad! Let's get the test part covered.

2025-03-03 21:27 UTC, leofang commented on cuda_core/cuda/core/experimental/_launcher.py
> +            raise ValueError("stream must either be a Stream object or support __cuda_stream__") from e
nit: can we move this to right after the `if stream is None` check? In particular, if stream is invalid we want to raise asap, and not creating a `config` object

2025-03-03 21:27 UTC, leofang commented on cuda_core/tests/test_launcher.py
> -        LaunchConfig(grid=(1, 1, 1), block=(1, 1, 1), stream="invalid_stream", shmem_size=0)
Let's keep this test (with some minor tweaks) to ensure ValueError is raised.

2025-03-03 21:50 UTC, vzhurba01 commented on cuda_core/cuda/core/experimental/_launcher.py
> +            raise ValueError("stream must either be a Stream object or support __cuda_stream__") from e
Already done as part of https://github.com/NVIDIA/cuda-python/pull/316/commits/3dd62c7074d170e6e64a5ab297f883c80e272358

2025-03-03 22:06 UTC, vzhurba01 commented
/ok to test

2025-03-03 22:06 UTC, vzhurba01 commented on cuda_core/tests/test_launcher.py
> -        LaunchConfig(grid=(1, 1, 1), block=(1, 1, 1), stream="invalid_stream", shmem_size=0)
Done

2025-03-03 22:13 UTC, leofang approved these changes

2025-03-03 22:32 UTC, merged